/** @type {import('tailwindcss').Config} */
module.exports = {
  blocklist: ["overline"],
  darkMode: ["class"],
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./app/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Instrument Sans"', "ui-sans-serif", "system-ui", "sans-serif"],
        serif: ['"Instrument Serif"', "Georgia", "serif"],
        mono: ['"JetBrains Mono"', "ui-monospace", "monospace"],
      },
      colors: {
        hg: {
          bg: "var(--bg)",
          surface: "var(--surface)",
          sunken: "var(--surface-sunken)",
          line: "var(--border)",
          text: "var(--text-primary)",
          text2: "var(--text-secondary)",
          muted: "var(--text-muted)",
          accent: "var(--accent)",
          accentHover: "var(--accent-hover)",
          supported: "var(--supported)",
          contradicted: "var(--contradicted)",
          insufficient: "var(--insufficient)",
          uncertain: "var(--uncertain)",
        },
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        card: { DEFAULT: "hsl(var(--card))", foreground: "hsl(var(--card-foreground))" },
        popover: { DEFAULT: "hsl(var(--popover))", foreground: "hsl(var(--popover-foreground))" },
        primary: { DEFAULT: "hsl(var(--primary))", foreground: "hsl(var(--primary-foreground))" },
        secondary: { DEFAULT: "hsl(var(--secondary))", foreground: "hsl(var(--secondary-foreground))" },
        muted: { DEFAULT: "hsl(var(--muted))", foreground: "hsl(var(--muted-foreground))" },
        accent: { DEFAULT: "hsl(var(--accent-ui))", foreground: "hsl(var(--accent-foreground))" },
        destructive: { DEFAULT: "hsl(var(--destructive))", foreground: "hsl(var(--destructive-foreground))" },
        border: "hsl(var(--border-ui))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      borderRadius: { lg: "var(--radius)", md: "calc(var(--radius) - 2px)", sm: "calc(var(--radius) - 4px)" },
      boxShadow: {
        hg: "0 1px 2px rgba(0,0,0,0.04), 0 8px 24px rgba(0,0,0,0.06)",
        "hg-lg": "0 2px 4px rgba(0,0,0,0.05), 0 24px 64px rgba(0,0,0,0.10)",
      },
      keyframes: {
        "accordion-down": { from: { height: "0" }, to: { height: "var(--radix-accordion-content-height)" } },
        "accordion-up": { from: { height: "var(--radix-accordion-content-height)" }, to: { height: "0" } },
        "hg-drift": { "0%,100%": { transform: "translateY(0)" }, "50%": { transform: "translateY(-5px)" } },
        "hg-rise": { from: { opacity: "0", transform: "translateY(10px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "hg-line": { from: { transform: "translateX(-100%)" }, to: { transform: "translateX(100%)" } },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "hg-drift": "hg-drift 6s ease-in-out infinite",
        "hg-rise": "hg-rise .5s cubic-bezier(.22,1,.36,1) both",
        "hg-line": "hg-line 1.6s cubic-bezier(.4,0,.2,1) infinite",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
