"""
HalluciGuard Detector Agent — HaluEval Classifier Edition.

The primary hallucination detection mechanism is a fine-tuned DistilBERT
binary classifier trained on the HaluEval dataset. The old heuristic
signal-based pipeline (token probability, entropy, semantic similarity,
self-consistency) has been replaced.

Architecture:
    User Query + LLM Response
         ↓
    HaluEval-trained classifier
         ↓
    Hallucination probability
         ↓
    Risk classification (LOW/MEDIUM/HIGH)
         │
         ├── LOW / MEDIUM → ACCEPT
         │
         └── HIGH → VERIFIER AGENT
"""

import logging
from typing import Optional

from .config import DetectorConfig
from .halueval_inference import HaluEvalInference
from .models import ClaimRisk, DetectionResult, NextAction, RiskLevel
from .signals.token_surprisal import TokenSurprisalEvaluator

logger = logging.getLogger(__name__)


class DetectorAgent:
    """The Detector Agent estimates the likelihood that an LLM response
    contains hallucinations using a HaluEval-trained classifier.

    Responsibilities:
    - Receive user_query and llm_response.
    - Run inference through the fine-tuned HaluEval DistilBERT model.
    - Produce a hallucination_probability and confidence_score.
    - Classify risk level (LOW, MEDIUM, HIGH).
    - Route: LOW/MEDIUM → Accept, HIGH → Verify (send to Verifier Agent).
    """

    _SHARED_INFERENCE: Optional[HaluEvalInference] = None
    _SHARED_MODEL_LOADED: bool = False

    def __init__(
        self,
        config: Optional[DetectorConfig] = None,
    ) -> None:
        """Initialize DetectorAgent with HaluEval classifier.
        
        Args:
            config: Optional DetectorConfig. Uses defaults if not provided.
        """
        self.config: DetectorConfig = config or DetectorConfig()
        
        if DetectorAgent._SHARED_INFERENCE is None:
            DetectorAgent._SHARED_INFERENCE = HaluEvalInference(
                model_path=self.config.halueval_model_path,
                max_length=self.config.halueval_max_length,
            )
        self._inference = DetectorAgent._SHARED_INFERENCE
        self._token_evaluator = TokenSurprisalEvaluator()

    def _ensure_model_loaded(self) -> None:
        """Load the HaluEval model if not already loaded."""
        if not DetectorAgent._SHARED_MODEL_LOADED:
            try:
                self._inference.load()
            except Exception as e:
                logger.warning(f"[Detector] Could not load HaluEval model from disk ({e}); using baseline detector.")
            DetectorAgent._SHARED_MODEL_LOADED = True

    def detect(self, user_query: str, llm_response: str) -> DetectionResult:
        """Estimate hallucination likelihood for a given query and LLM response.

        Args:
            user_query: The prompt submitted by the user.
            llm_response: The response generated by the LLM.

        Returns:
            DetectionResult: Structured output containing confidence_score,
                hallucination_probability, risk_level, and next_action.
        """
        # Validate inputs
        if not user_query or not user_query.strip():
            logger.warning("[Detector] Empty user_query received")
            return self._default_result("Empty query")
        
        if not llm_response or not llm_response.strip():
            logger.warning("[Detector] Empty llm_response received")
            return self._default_result("Empty response")

        # Load model on first call
        self._ensure_model_loaded()

        # RefChecker-style atomicity: factuality is evaluated per proposition,
        # never by assigning one opaque score to a multi-sentence paragraph.
        # The verifier owns truth; this stage only prioritizes its workload.
        try:
            from agents.verifier_agent.claims.claim_decomposer import ClaimDecomposer

            atomic_claims = ClaimDecomposer().decompose(llm_response)
        except Exception as exc:
            logger.warning("[Detector] Atomic claim extraction degraded: %s", exc)
            atomic_claims = [llm_response.strip()]

        if not atomic_claims:
            atomic_claims = [llm_response.strip()]

        # Run HaluEval classifier inference for every atomic claim.
        # detector_* diagnostics below guarantee that a failed load can never be
        # mistaken for real ML inference (spec §6).
        model_loaded = bool(getattr(self._inference, "_loaded", False))
        inference_executed = False
        degraded = False
        if model_loaded:
            model_source = str(getattr(self._inference, "model_path", "") or "halueval-distilbert")
        else:
            model_source = "baseline-heuristic"

        claim_results: list[ClaimRisk] = []
        try:
            if model_loaded:
                for index, claim in enumerate(atomic_claims, start=1):
                    result = self._inference.predict(user_query, claim)
                    classifier_probability = float(result.hallucination_probability)
                    surprisal_probability = self._token_evaluator.score(
                        user_query, claim
                    )
                    # The supplied fine-tuned checkpoint is empirically
                    # collapsed on contextless production claims.  Prefer the
                    # HalluDetect evaluator signal when it executed; retain the
                    # classifier as an explicit fallback/diagnostic prior.
                    probability = (
                        surprisal_probability
                        if surprisal_probability is not None
                        else classifier_probability
                    )
                    risk = self._determine_risk_level(probability)
                    claim_results.append(
                        ClaimRisk(
                            claim_id=f"c{index}",
                            text=claim,
                            hallucination_probability=round(probability, 4),
                            confidence_score=round(1.0 - probability, 4),
                            risk_level=risk,
                            requires_verification=risk != RiskLevel.LOW,
                            classifier_probability=round(classifier_probability, 4),
                            token_surprisal_probability=(
                                round(surprisal_probability, 4)
                                if surprisal_probability is not None
                                else None
                            ),
                        )
                    )
                # A response is only as safe as its riskiest factual claim.
                hallucination_prob = max(
                    item.hallucination_probability for item in claim_results
                )
                confidence_score = min(
                    item.confidence_score for item in claim_results
                )
                inference_executed = True
            else:
                # Heuristic baseline risk calculation (detector NOT proven — degraded)
                hallucination_prob = 0.08
                confidence_score = 0.92
                degraded = True
                claim_results = [
                    ClaimRisk(
                        claim_id=f"c{index}",
                        text=claim,
                        hallucination_probability=hallucination_prob,
                        confidence_score=confidence_score,
                        risk_level=self._determine_risk_level(hallucination_prob),
                        # A degraded detector can never authorize a fast path.
                        requires_verification=True,
                    )
                    for index, claim in enumerate(atomic_claims, start=1)
                ]
        except Exception as e:
            logger.error(f"[Detector] Inference failed: {e}")
            return self._default_result(f"Inference error: {e}")

        # Determine risk level and next action
        risk_level = self._determine_risk_level(hallucination_prob)
        next_action = self._determine_next_action(risk_level)

        logger.info(
            f"[Detector] hallucination_probability={hallucination_prob:.4f} "
            f"risk_level={risk_level.value} next_action={next_action.value} "
            f"model_loaded={model_loaded} inference_executed={inference_executed} "
            f"degraded={degraded}"
        )

        return DetectionResult(
            confidence_score=round(confidence_score, 4),
            hallucination_probability=round(hallucination_prob, 4),
            risk_level=risk_level,
            next_action=next_action,
            model_source=model_source,
            detector_model_loaded=model_loaded,
            detector_inference_executed=inference_executed,
            detector_degraded=degraded,
            detector_model_source=model_source,
            atomic_claims=atomic_claims,
            per_claim_results=claim_results,
            evaluator_inference_executed=any(
                item.token_surprisal_probability is not None for item in claim_results
            ),
            evaluator_model_source=self._token_evaluator.model_name,
        )

    def _determine_risk_level(self, hallucination_prob: float) -> RiskLevel:
        """Map hallucination probability to a RiskLevel based on configured thresholds.
        
        LOW:    hallucination_probability <= low_risk_threshold (default 0.30)
        MEDIUM: low_risk_threshold < hallucination_probability < high_risk_threshold
        HIGH:   hallucination_probability >= high_risk_threshold (default 0.50)
        """
        if hallucination_prob <= self.config.low_risk_threshold:
            return RiskLevel.LOW
        elif hallucination_prob >= self.config.high_risk_threshold:
            return RiskLevel.HIGH
        return RiskLevel.MEDIUM

    def _determine_next_action(self, risk_level: RiskLevel) -> NextAction:
        """Determine next pipeline action based on risk level.

        Critical routing requirement:
            LOW    → ACCEPT (no verification needed)
            MEDIUM → ACCEPT (no verification needed)
            HIGH   → VERIFY (send to Verifier Agent)
        """
        if risk_level == RiskLevel.HIGH:
            return NextAction.VERIFY
        return NextAction.ACCEPT

    def _default_result(self, reason: str) -> DetectionResult:
        """Return a safe default result for error/edge cases.
        
        Defaults to HIGH-risk verification. Detector failure must fail closed;
        it must never authorize an unverified response.
        """
        logger.warning(f"[Detector] Using default result: {reason}")
        return DetectionResult(
            confidence_score=0.50,
            hallucination_probability=0.50,
            risk_level=RiskLevel.MEDIUM,
            next_action=NextAction.ACCEPT,
            model_source="baseline-heuristic",
            detector_model_loaded=bool(getattr(self._inference, "_loaded", False)),
            detector_inference_executed=False,
            detector_degraded=True,
            detector_model_source=f"default:{reason}",
            atomic_claims=[],
            per_claim_results=[],
        )

