"""
HalluciGuard Detector Agent — HaluEval Classifier Edition.

The primary hallucination detection mechanism is a fine-tuned DistilBERT
binary classifier trained on the HaluEval dataset. The old heuristic
signal-based pipeline (token probability, entropy, semantic similarity,
self-consistency) has been replaced.

Architecture:
    User Query + LLM Response
         ↓
    HaluEval-trained classifier
         ↓
    Hallucination probability
         ↓
    Risk classification (LOW/MEDIUM/HIGH)
         └── All risk tiers → VERIFIER AGENT (safe default)
"""

import logging
import math
from typing import Optional

from .config import DetectorConfig
from .halueval_inference import HaluEvalInference
from .models import DetectionResult, NextAction, RiskLevel
from .evidence import prepare_evidence

logger = logging.getLogger(__name__)


class DetectorAgent:
    """The Detector Agent estimates the likelihood that an LLM response
    contains hallucinations using a HaluEval-trained classifier.

    Responsibilities:
    - Receive user_query and llm_response.
    - Run inference through the fine-tuned HaluEval DistilBERT model.
    - Produce a hallucination_probability and confidence_score.
    - Classify risk level (LOW, MEDIUM, HIGH).
    - Route every result to the Verifier until a calibrated fast path is validated.
    """

    def __init__(
        self,
        config: Optional[DetectorConfig] = None,
        device: Optional[str] = None,
    ) -> None:
        """Initialize DetectorAgent with HaluEval classifier.
        
        Args:
            config: Optional DetectorConfig. Uses defaults if not provided.
        """
        self.config: DetectorConfig = config or DetectorConfig()
        
        self._inference = HaluEvalInference(
            model_path=self.config.halueval_model_path,
            max_length=self.config.halueval_max_length,
            device=device,
        )

    def _ensure_model_loaded(self) -> bool:
        """Load the HaluEval model if not already loaded."""
        try:
            self._inference.load()
            return bool(self._inference.is_loaded())
        except Exception as exc:
            logger.warning("[Detector] HaluEval model unavailable (%s)", type(exc).__name__)
            return False

    def detect(self, user_query: str, llm_response: str, evidence=None) -> DetectionResult:
        """Estimate hallucination likelihood for a given query and LLM response.

        Args:
            user_query: The prompt submitted by the user.
            llm_response: The response generated by the LLM.

        Returns:
            DetectionResult: Structured output containing confidence_score,
                hallucination_probability, risk_level, and next_action.
        """
        # Validate inputs
        if not user_query or not user_query.strip():
            logger.warning("[Detector] Empty user_query received")
            return self._default_result("Empty query")
        
        if not llm_response or not llm_response.strip():
            logger.warning("[Detector] Empty llm_response received")
            return self._default_result("Empty response")

        # Load model on first call
        prepared = prepare_evidence(evidence)
        if not self._ensure_model_loaded():
            return self._default_result("model_unavailable", prepared.diagnostics())

        # Run HaluEval classifier inference
        try:
            result = self._inference.predict(user_query, llm_response,
                                             context=prepared.context or None)
            hallucination_prob = float(result.hallucination_probability)
            confidence_score = float(result.confidence_score)
            if not all(math.isfinite(v) and 0 <= v <= 1 for v in (hallucination_prob, confidence_score)):
                raise ValueError("invalid model probability")
        except Exception as exc:
            logger.error("[Detector] Inference failed (%s)", type(exc).__name__)
            return self._default_result("inference_failed", prepared.diagnostics())

        # Determine risk level and next action
        risk_level = self._determine_risk_level(hallucination_prob)
        next_action = self._determine_next_action(risk_level)

        logger.info(
            f"[Detector] hallucination_probability={hallucination_prob:.4f} "
            f"risk_level={risk_level.value} next_action={next_action.value}"
        )

        return DetectionResult(
            confidence_score=round(confidence_score, 4),
            hallucination_probability=round(hallucination_prob, 4),
            risk_level=risk_level,
            next_action=next_action,
            status="degraded" if prepared.diagnostics()["degraded"] else "completed",
            model_loaded=True,
            inference_executed=True,
            probability_available=True,
            calibrated=False,
            grounded=bool(prepared.context),
            detector_degraded=prepared.diagnostics()["degraded"],
            diagnostics={"model_path": str(self._inference.model_path),
                         "device": self._inference.device,
                         "max_length": self._inference.max_length,
                         "evidence": prepared.diagnostics(),
                         "model_input": result.input_diagnostics or {}},
        )

    def _determine_risk_level(self, hallucination_prob: float) -> RiskLevel:
        """Map hallucination probability to a RiskLevel based on configured thresholds.
        
        LOW:    hallucination_probability <= low_risk_threshold (default 0.30)
        MEDIUM: low_risk_threshold < hallucination_probability < high_risk_threshold
        HIGH:   hallucination_probability >= high_risk_threshold (default 0.50)
        """
        if hallucination_prob <= self.config.low_risk_threshold:
            return RiskLevel.LOW
        elif hallucination_prob >= self.config.high_risk_threshold:
            return RiskLevel.HIGH
        return RiskLevel.MEDIUM

    def _determine_next_action(self, risk_level: RiskLevel) -> NextAction:
        """Determine next pipeline action based on risk level.

        The current HaluEval checkpoint has no certified low-risk bypass.
        All risk tiers therefore request evidence-based verification.
        """
        # A classifier score is triage, not proof. No calibrated fast path is
        # enabled for this checkpoint, including LOW/MEDIUM predictions.
        return NextAction.VERIFY

    def _default_result(self, reason: str, evidence_diagnostics: dict | None = None) -> DetectionResult:
        """Return a safe default result for error/edge cases.

        Missing model inference has no meaningful numeric probability.
        """
        logger.warning("[Detector] Verification required (%s)", reason)
        return DetectionResult(
            confidence_score=None,
            hallucination_probability=None,
            risk_level=RiskLevel.HIGH,
            next_action=NextAction.VERIFY,
            status="failed",
            model_loaded=bool(self._inference.is_loaded()),
            inference_executed=False,
            probability_available=False,
            calibrated=False,
            detector_degraded=True,
            diagnostics={"failure_reason": reason,
                         "model_path": str(self._inference.model_path),
                         "device": self._inference.device,
                         "max_length": self._inference.max_length,
                         "evidence": evidence_diagnostics or {}},
        )

