import math
from typing import Optional
from .config import DetectorConfig
from .gate import SelfConsistencyGate
from .model_manager import ModelManager
from .models import (
    DetectionResult,
    EntropyMetrics,
    NextAction,
    RiskLevel,
    SemanticSimilarityMetrics,
    SelfConsistencyMetrics,
    SignalMetricsDetail,
    TokenProbabilityMetrics,
)
from .signals.entropy import EntropyCalculator
from .signals.semantic_similarity import SemanticSimilarityCalculator
from .signals.self_consistency import SelfConsistencyCalculator


class DetectorAgent:
    """The Detector Agent estimates the likelihood that an LLM response contains hallucinations.
    
    Responsibilities:
    - Receive user_query and llm_response.
    - Compute single-pass statistical signals (Token Probability, Entropy, Semantic Similarity).
    - Evaluate Intelligent Gating (SelfConsistencyGate) to execute Self-Consistency ONLY when:
        Condition A: Single-pass risk level is MEDIUM.
        Condition B: User query category is an analytical category (factual, explanation, summarization, reasoning).
    - Synthesize signals dynamically in _aggregate_scores() using weights configured in DetectorConfig.
    - Categorize final risk level (LOW, MEDIUM, HIGH) and recommend pipeline next action (Accept or Verify).
    """

    def __init__(
        self,
        config: Optional[DetectorConfig] = None,
        model_manager: Optional[ModelManager] = None
    ) -> None:
        """Initialize DetectorAgent with configuration, shared ModelManager, and SelfConsistencyGate."""
        self.config: DetectorConfig = config or DetectorConfig()
        self.model_manager: ModelManager = model_manager or ModelManager(model_name=self.config.model_name)
        self.entropy_calculator: EntropyCalculator = EntropyCalculator(self.model_manager)
        self.semantic_calculator: SemanticSimilarityCalculator = SemanticSimilarityCalculator(self.model_manager)
        self.self_consistency_calculator: SelfConsistencyCalculator = SelfConsistencyCalculator(
            model_manager=self.model_manager,
            config=self.config
        )
        self.gate: SelfConsistencyGate = SelfConsistencyGate()

    def detect(self, user_query: str, llm_response: str) -> DetectionResult:
        """Estimate hallucination likelihood for a given query and LLM response.
        
        Args:
            user_query: The prompt submitted by the user.
            llm_response: The response generated by the LLM.
            
        Returns:
            DetectionResult: Structured output containing confidence_score, hallucination_probability,
                             risk_level, next_action, and per-signal metrics breakdown.
        """
        # Step 1: Compute single-pass statistical detection signals
        token_prob_metrics = self._compute_token_probability(user_query, llm_response)
        entropy_metrics = self._compute_entropy(user_query, llm_response)
        semantic_sim_metrics = self._compute_semantic_similarity(user_query, llm_response)

        # Step 2: Calculate initial single-pass confidence and risk level
        single_pass_conf, single_pass_halluc = self._aggregate_scores(
            token_prob_metrics, entropy_metrics, semantic_sim_metrics, self_consist_metrics=None
        )
        initial_risk_level = self._determine_risk_level(single_pass_halluc)

        # Step 3: Evaluate Intelligent Gating for Self-Consistency
        should_run, log_reason, category = self.gate.should_run_self_consistency(
            user_query=user_query, current_risk_level=initial_risk_level
        )
        print(log_reason)

        # Step 4: Execute Self-Consistency conditionally based on gate decision
        self_consist_metrics = None
        if should_run:
            self_consist_metrics = self._compute_self_consistency(user_query, llm_response)

        # Step 5: Synthesize final scores dynamically using DetectorConfig weights
        confidence_score, hallucination_prob = self._aggregate_scores(
            token_prob_metrics, entropy_metrics, semantic_sim_metrics, self_consist_metrics
        )

        # Step 6: Categorize final risk level and next action
        risk_level = self._determine_risk_level(hallucination_prob)
        next_action = self._determine_next_action(risk_level)

        # Build detailed per-signal metrics breakdown
        metrics_detail = SignalMetricsDetail(
            token_probability=token_prob_metrics,
            entropy=entropy_metrics,
            semantic_similarity=semantic_sim_metrics,
            self_consistency=self_consist_metrics
        )

        return DetectionResult(
            confidence_score=confidence_score,
            hallucination_probability=hallucination_prob,
            risk_level=risk_level,
            next_action=next_action,
            metrics=metrics_detail
        )

    def _aggregate_scores(
        self,
        token_prob_metrics: Optional[TokenProbabilityMetrics],
        entropy_metrics: Optional[EntropyMetrics],
        semantic_sim_metrics: Optional[SemanticSimilarityMetrics],
        self_consist_metrics: Optional[SelfConsistencyMetrics]
    ) -> tuple[float, float]:
        """Combine available signal metrics into final confidence score and hallucination probability.
        
        Reads weights strictly from self.config.signal_weights.
        """
        weights = self.config.signal_weights
        scores = []
        applied_weights = []

        if token_prob_metrics is not None:
            exp_conf = math.exp(token_prob_metrics.avg_logprob)
            scores.append(max(0.0, min(1.0, exp_conf)))
            applied_weights.append(weights.token_probability)

        if entropy_metrics is not None:
            entropy_certainty = 1.0 - entropy_metrics.normalized_entropy
            scores.append(max(0.0, min(1.0, entropy_certainty)))
            applied_weights.append(weights.entropy)

        if semantic_sim_metrics is not None:
            semantic_certainty = semantic_sim_metrics.normalized_similarity
            scores.append(max(0.0, min(1.0, semantic_certainty)))
            applied_weights.append(weights.semantic_similarity)

        if self_consist_metrics is not None:
            consistency_certainty = self_consist_metrics.consistency_score
            scores.append(max(0.0, min(1.0, consistency_certainty)))
            applied_weights.append(weights.self_consistency)

        if scores:
            total_weight = sum(applied_weights)
            if total_weight > 0:
                weighted_score = sum(s * w for s, w in zip(scores, applied_weights)) / total_weight
                confidence_score = round(max(0.0, min(1.0, weighted_score)), 4)
                hallucination_prob = round(1.0 - confidence_score, 4)
            else:
                confidence_score = self.config.default_confidence_score
                hallucination_prob = self.config.default_hallucination_prob
        else:
            confidence_score = self.config.default_confidence_score
            hallucination_prob = self.config.default_hallucination_prob

        return confidence_score, hallucination_prob

    def _determine_risk_level(self, hallucination_prob: float) -> RiskLevel:
        """Map hallucination probability to a RiskLevel based on configured thresholds."""
        if hallucination_prob <= self.config.low_risk_threshold:
            return RiskLevel.LOW
        elif hallucination_prob >= self.config.high_risk_threshold:
            return RiskLevel.HIGH
        return RiskLevel.MEDIUM

    def _determine_next_action(self, risk_level: RiskLevel) -> NextAction:
        """Determine next pipeline action based on risk level.
        
        LOW risk responses are accepted immediately.
        MEDIUM and HIGH risk responses trigger downstream verification.
        """
        if risk_level == RiskLevel.LOW:
            return NextAction.ACCEPT
        return NextAction.VERIFY

    # ------------------------------------------------------------------
    # Signal Detection Implementations & Extension Hooks
    # ------------------------------------------------------------------

    def _compute_token_probability(
        self, user_query: str, llm_response: str
    ) -> Optional[TokenProbabilityMetrics]:
        """Extract raw token log probability metrics (avg_logprob, min_logprob, low_confidence_ratio)."""
        try:
            import torch

            tokenizer, model = self.model_manager.get_model_and_tokenizer()
            if tokenizer is None or model is None:
                return None

            prompt_text = f"User: {user_query}\nAssistant:"
            full_text = f"{prompt_text} {llm_response}"

            prompt_ids = tokenizer(prompt_text, return_tensors="pt")["input_ids"]
            full_inputs = tokenizer(full_text, return_tensors="pt")
            full_ids = full_inputs["input_ids"]

            prompt_len = prompt_ids.shape[1]
            seq_len = full_ids.shape[1]

            if seq_len <= prompt_len:
                return None

            with torch.no_grad():
                outputs = model(**full_inputs)
                logits = outputs.logits

            log_probs = torch.log_softmax(logits, dim=-1)

            response_log_probs = []
            for i in range(prompt_len, seq_len):
                target_token_id = full_ids[0, i]
                token_log_prob = log_probs[0, i - 1, target_token_id].item()
                response_log_probs.append(token_log_prob)

            if not response_log_probs:
                return None

            avg_logprob = sum(response_log_probs) / len(response_log_probs)
            min_logprob = min(response_log_probs)
            
            threshold = self.config.low_confidence_logprob_threshold
            low_conf_count = sum(1 for lp in response_log_probs if lp < threshold)
            low_confidence_ratio = low_conf_count / len(response_log_probs)

            return TokenProbabilityMetrics(
                avg_logprob=round(avg_logprob, 6),
                min_logprob=round(min_logprob, 6),
                low_confidence_ratio=round(low_confidence_ratio, 4)
            )

        except Exception as e:
            print(f"[DetectorAgent] Warning: Token probability computation failed: {e}")
            return None

    def _compute_entropy(self, user_query: str, llm_response: str) -> Optional[EntropyMetrics]:
        """Compute predictive entropy metrics for response sequence using EntropyCalculator module."""
        return self.entropy_calculator.compute(user_query, llm_response)

    def _compute_semantic_similarity(
        self, user_query: str, llm_response: str
    ) -> Optional[SemanticSimilarityMetrics]:
        """Compute semantic similarity metrics using SemanticSimilarityCalculator module."""
        return self.semantic_calculator.compute(user_query, llm_response)

    def _compute_self_consistency(
        self, user_query: str, llm_response: str
    ) -> Optional[SelfConsistencyMetrics]:
        """Compute self-consistency metrics using SelfConsistencyCalculator module."""
        metrics, _, _ = self.self_consistency_calculator.compute(user_query=user_query)
        return metrics
