"""
HalluciGuard Detector Agent — Staging Edition.

Coordinates HaluEval model inference, threshold evaluation, and downstream routing.
Preserves all diagnostic telemetry and risk classification boundaries.
"""

import logging
from typing import Optional

from .config import DetectorConfig
from .halueval_inference import HaluEvalInference
from .models import DetectionResult, NextAction, RiskLevel

logger = logging.getLogger("halluciguard.detector")


class DetectorAgent:
    """Estimates the likelihood that an LLM response contains hallucinations
    using a fine-tuned HaluEval DistilBERT classifier.
    """

    _SHARED_INFERENCE: Optional[HaluEvalInference] = None
    _SHARED_MODEL_LOADED: bool = False

    def __init__(
        self,
        config: Optional[DetectorConfig] = None,
    ) -> None:
        """Initialize DetectorAgent with HaluEval classifier config."""
        self.config: DetectorConfig = config or DetectorConfig()

        if DetectorAgent._SHARED_INFERENCE is None:
            DetectorAgent._SHARED_INFERENCE = HaluEvalInference(
                model_path=self.config.halueval_model_path,
                max_length=self.config.halueval_max_length,
            )
        self._inference = DetectorAgent._SHARED_INFERENCE

    def _ensure_model_loaded(self) -> None:
        """Load the HaluEval model if not already loaded."""
        if not DetectorAgent._SHARED_MODEL_LOADED:
            try:
                self._inference.load()
            except Exception as e:
                logger.warning(
                    f"[Detector] Could not load HaluEval model ({e}); using degraded baseline mode."
                )
                print(f"[Detector] WARNING: Model loading failed ({e}); degraded baseline active.")
            DetectorAgent._SHARED_MODEL_LOADED = True

    def detect(
        self,
        user_query: str,
        llm_response: str,
        context: Optional[str] = None,
    ) -> DetectionResult:
        """Estimate hallucination likelihood for a given query, response, and optional context.

        Args:
            user_query: The prompt submitted by the user.
            llm_response: The response generated by the LLM.
            context: Optional grounding reference context.

        Returns:
            DetectionResult: Structured output containing confidence_score,
                hallucination_probability, risk_level, and next_action.
        """
        # Validate inputs
        if not user_query or not user_query.strip():
            logger.warning("[Detector] Empty user_query received")
            return self._default_result("Empty query")

        if not llm_response or not llm_response.strip():
            logger.warning("[Detector] Empty llm_response received")
            return self._default_result("Empty response")

        # Load model on first call
        self._ensure_model_loaded()

        model_loaded = bool(getattr(self._inference, "_loaded", False))
        inference_executed = False
        degraded = False

        if model_loaded:
            model_source = str(getattr(self._inference, "model_path", "") or "Manjunath2000006/halluciguard-detector")
        else:
            model_source = "baseline-heuristic"

        try:
            if model_loaded:
                result = self._inference.predict(user_query, llm_response, context=context)
                hallucination_prob = result.hallucination_probability
                confidence_score = result.confidence_score
                inference_executed = True
            else:
                # Degraded fallback mode
                hallucination_prob = 0.08
                confidence_score = 0.92
                degraded = True
        except Exception as e:
            logger.error(f"[Detector] Inference execution failed: {e}")
            return self._default_result(f"Inference error: {e}")

        # Determine risk level and routing action
        risk_level = self._determine_risk_level(hallucination_prob)
        next_action = self._determine_next_action(risk_level)

        logger.info(
            f"[RESULT] risk_level={risk_level.value} next_action={next_action.value} "
            f"model_loaded={model_loaded} inference_executed={inference_executed} "
            f"degraded={degraded}"
        )
        print(
            f"[RESULT] risk_level={risk_level.value} next_action={next_action.value} "
            f"inference_executed={inference_executed}"
        )

        return DetectionResult(
            confidence_score=round(confidence_score, 4),
            hallucination_probability=round(hallucination_prob, 4),
            risk_level=risk_level,
            next_action=next_action,
            model_source=model_source,
            detector_model_loaded=model_loaded,
            detector_inference_executed=inference_executed,
            detector_degraded=degraded,
            detector_model_source=model_source,
        )

    def _determine_risk_level(self, hallucination_prob: float) -> RiskLevel:
        """Map hallucination probability to a RiskLevel based on configured thresholds.

        LOW:    hallucination_probability <= low_risk_threshold (default 0.30)
        MEDIUM: low_risk_threshold < hallucination_probability < high_risk_threshold
        HIGH:   hallucination_probability >= high_risk_threshold (default 0.50)
        """
        if hallucination_prob <= self.config.low_risk_threshold:
            return RiskLevel.LOW
        elif hallucination_prob >= self.config.high_risk_threshold:
            return RiskLevel.HIGH
        return RiskLevel.MEDIUM

    def _determine_next_action(self, risk_level: RiskLevel) -> NextAction:
        """Determine next pipeline action based on risk level.

        LOW    → ACCEPT
        MEDIUM → ACCEPT
        HIGH   → VERIFY
        """
        if risk_level == RiskLevel.HIGH:
            return NextAction.VERIFY
        return NextAction.ACCEPT

    def _default_result(self, reason: str) -> DetectionResult:
        """Return a safe default result for edge cases and errors."""
        logger.warning(f"[Detector] Using default result: {reason}")
        return DetectionResult(
            confidence_score=0.50,
            hallucination_probability=0.50,
            risk_level=RiskLevel.MEDIUM,
            next_action=NextAction.ACCEPT,
            model_source="baseline-heuristic",
            detector_model_loaded=bool(getattr(self._inference, "_loaded", False)),
            detector_inference_executed=False,
            detector_degraded=True,
            detector_model_source=f"default:{reason}",
        )
